### ISSUE TITLE
Global options in root of script

### ISSUE THREAD

**Issue by sh1ngekyo** [sh1ngekyo/macropse#2]
We need some options that will works for all script.
* delay for keyboard handler cuz now it procs many times while pressing signals're received. For my system optimal value is 100. Also need to create default value.
* rebinds for keys, sample: A = B.
* bind for pause all script.

for example:
```
<root delay="100" rebind="A=S, D=F" pause="F8">
```

**Comment by meltway** [comment]
Please, add an option to run only when window is active or on top
