### ISSUE TITLE
Some remarks

### ISSUE THREAD

**Issue by Meelto** [sh1ngekyo/macropse#4]
1. Использовать Thread.Sleep для ожидания, например, в команде delay или цикле – плохая практика.
2. Драйвер хорошо работает на 1903, но появляются проблемы на 2004 и, скорее всего, версиях выше. У меня отвалился realtek hda и иногда при спаме клавиш вылетают совершенно не те, что были указаны. Полагаю, проблема в самом драйвере.
3. Стоит указать в будущем, что билдить нужно под x64 only.
4. В новых версиях AA они изменили защиту. Теперь не пропускает эту программу. Есть варианты как обойти?

**Comment by sh1ngekyo** [comment]
> 1. Использовать Thread.Sleep для ожидания, например, в команде delay или цикле – плохая практика.

Знаю, потом исправлю. Вообще лучше пока использовать предидущую версию, эта еще не готова.
> 2. Драйвер хорошо работает на 1903, но появляются проблемы на 2004 и, скорее всего, версиях выше. У меня отвалился realtek hda и иногда при спаме клавиш вылетают совершенно не те, что были указаны. Полагаю, проблема в самом драйвере.

У меня пока нет возможности тестить на всех версиях десятки. Вероятно, проблема в драйвере, постараюсь посмотреть в чем может быть проблема.
> 3. Стоит указать в будущем, что билдить нужно под x64 only.

Предидущую версию тоже, позже добавлю. Опять же - этот проект пока не готов для использования, разве что некоторые модули.
> 4. В новых версиях AA они изменили защиту. Теперь не пропускает эту программу. Есть варианты как обойти?

С правами запускать нужно. Если и это не поможет, попробуйте запускать клиент на который завязан АА и после этого скрипт с админа. Предидущая версия также не работает после обновы АА? Проверю, отвечу.

**Comment by Meelto** [comment]
@sh1ngekyo 
> С правами запускать нужно.

Запускаю с правами
> попробуйте запускать клиент на который завязан АА и после этого скрипт с админа.

Хм, странно, работает. С этими манипуляциями работает и прошлая версия

**Comment by sh1ngekyo** [comment]
Тестил на 2004, драйвер и правда отваливается. Пересобрал у себя, все работает. Позже выложу все исходники.
